### ISSUE TITLE
Can't run the static scene grasping block on custom data

### ISSUE THREAD

**Issue by PannagaS** [jimazeyu/GraspSplats#6]
Hi, first of all, this is a phenomenal paper and very well implemented. I was trying to implement this on the given **example_data**, which worked fine without any errors. 

However, when I try to run the entire implementation on my **custom data set**, I can't run the **static scene grasping** command - 
`python realbot_ui.py -m outputs/path_to_my_data`

So, I started debugging and found that the keys of **feat_decoder.pth** is NOT SAME for the example data and for my custom data. I printed the keys of feat_decoder.pth for both the datasets; 

For example_data, I am getting - 
<img width="1053" alt="image" src="https://github.com/user-attachments/assets/a2b1d8a0-3bb3-49ae-8119-10e9a2c7b9fc">

And, for my custom_data, I am getting - 
<img width="1044" alt="image" src="https://github.com/user-attachments/assets/6e5f6da3-6950-4e0c-91c4-1574f4da2599">

As you can see, in the feat_decoder.pth that is generated for my custom_data, I am NOT having **'part_conv1.bias', 'part_conv1.weight_g', 'part_conv1.weight_v'** keys. 

This is causing an issue when I run - `python realbot_ui.py -m outputs/path_to_my_data`. How do I fix this? 
Any help to resolve this issue is deeply appreciated. 

PS : In case the screenshot of the terminal is not super clear, I also wrote it down for reference - 
![image](https://github.com/user-attachments/assets/58216894-a1ab-477e-9a77-45bc98095a12)

Thank you!

**Comment by jimazeyu** [comment]
I think you forgot to add "--feature_type "clip_part" when computing the features:
_python feature-splatting-inria/train.py -s scene_data/example_data -m outputs/example_data --iterations 3000 --feature_type "clip_part"_

**Comment by PannagaS** [comment]
Yes, I realize that now. Thank you very much @jimazeyu .
