### ISSUE TITLE
How to get world2base transform with known gt metric scale pose?

### ISSUE THREAD

**Issue by kaixuanwang2003** [jimazeyu/GraspSplats#7]
Hi, thanks for open-sourcing your great work!

I tried to run GraspSplats in simulation, where I can get gt metric scale camera poses so there's no need to do calibration. I generate the colmap database and the gaussian splats was trained successfully.

The pose I wrote into colmap is the pose with metric scale, and the origin coincides with the base link of the robot. So I suppose `world2base` to be a `np.eye(4)`, but when I visualize the point cloud and the robot with `realbot_ui.py`, it seems that there's still a non-uni transform between the world frame and the robot base.

Do you have any ideas on that? Thank you for your time and help.

**Comment by jimazeyu** [comment]
world coordinates is just the origin of colmap, base coordinates is the base of your robot arm. If all the coordinates in your colmap is in the robot base frame, then it should be np.eye(4).

**Comment by kaixuanwang2003** [comment]
Thank you for your reply.

Is the `cameras.json` in the output path the value parsed from colmap? I found it different from the colmap input.

**Comment by jimazeyu** [comment]
The colmap input is in sparse/0, not sparse. The files in sparse isn't calibrated. Is the camera poses in sparse/0 the same as the output

**Comment by kaixuanwang2003** [comment]
Oh I see, I just wrote the gt poses into `sparse/`, I will check that later. Thank you for your help!

**Comment by kaixuanwang2003** [comment]
Thank you. I've changed the COLMAP output path to `sparse/0` and with world2base as np.eye(4) the visualization works as expected.
And just to confirm, is the selected grasp https://github.com/jimazeyu/GraspSplats/blob/76ee90bb018346a801f10fe42e5b70ff9bfbeda6/realbot_ui.py#L491C42-L491C50 represents a grasp2world (in this case also grasp2base) transform?

**Comment by jimazeyu** [comment]
It is in base coordinates
